name: "Check, Build, Release & Publish"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  
    name: "Check, Build, Release & Publish"
    steps:
      - name: "Get Code?"
        uses: actions/checkout@v1
      - name: "Check Code"
        uses: ./.github/actions/check