name: "Check"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  
    name: "Check"
    steps:
      - name: "Get Code"
        uses: actions/checkout@v1
      - name: "Check Code"
        uses: ./.github/actions/check