name: "Check, Build, Release & Publish"
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build:
    runs-on: ubuntu-latest  
    name: "Check, Build, Release & Publish"
    steps:
      - name: "Get Code"
        uses: actions/checkout@v1
      - name: "Check Code"
        uses: ./.github/actions/check
      - name: "Create Release"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: "false"
          prerelease: "false"
      - name: "Publish to VS Marketplace"
        uses: ./.github/actions/publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}